### PR TITLE
Fix email deliverability error log

### LINKED ISSUE #330: Emails do not deliver
Hi all,

Has anyone tried to use any of the auth actions (Email2FA or EmailActivator) and got an email delivered? 

I've tried severally using gmail's smpt, cpanel email, etc, none delivered. I only got the message:
```
Cannot send email for user: kuqib@mailinator.com
```

First, the code does not help in knowing the exact error as one can not see the actual problem with `printDebugger()`: https://github.com/codeigniter4/shield/blob/835bec6a6bfde617f5f5c3f14935e8b61282c20b/src/Authentication/Actions/EmailActivator.php#L50-L52 and when I tried to edit the code to show the exact error message, I got this `EXIM` error:
```
We do not authorize the use of this system to transport unsolicited,  and/or bulk e-mail
```
Secondly, I recently tried using phpmailer (by extending the default activator class) with the same email settings and mails delivered successfully. But then, I couldn't get the code to be sent as it is called from a private method:
https://github.com/codeigniter4/shield/blob/835bec6a6bfde617f5f5c3f14935e8b61282c20b/src/Authentication/Actions/EmailActivator.php#L104-L120

So, here's what I'm proposing:
* Can we have the default auth actions display or log the exact email error if it fails, for proper debugging?
* Can we also make the `createIdentity()` method a protected method instead of a private method so it can be used by child classes?

What do you think guys? I can make a PR if that's okay.

### PR DESCRIPTION
**Pull request by sammyskills**
Fixes #330

In this commit, 
* I updated the code to show a more detailed error if an email is not sent

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending PR!

Can you show a real example of the new error message?

**Comment by sammyskills** [comment]
Here's a sample error message:

```
CRITICAL - 2022-08-05 16:28:03 --> Cannot send email for user: kuqib@mailinator.com, 220-business67.web-hosting.com ESMTP Exim 4.95 #2 Fri, 05 Aug 2022 11:27:56 -0400 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
<br /><pre>hello: 250-business67.web-hosting.com Hello localhost [197.242.98.221]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPE_CONNECT
250-AUTH PLAIN LOGIN
250 HELP
</pre><pre>from: 250 OK
</pre><pre>to: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
</pre>The following SMTP error was encountered: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
<br /><pre>quit: 221 business67.web-hosting.com closing connection
</pre>Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br />220-business67.web-hosting.com ESMTP Exim 4.95 #2 Fri, 05 Aug 2022 11:27:59 -0400 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
<br /><pre>hello: 250-business67.web-hosting.com Hello localhost [197.242.98.221]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPE_CONNECT
250-AUTH PLAIN LOGIN
250 HELP
</pre><pre>from: 250 OK
</pre><pre>to: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
</pre>The following SMTP error was encountered: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
<br /><pre>quit: 221 business67.web-hosting.com closing connection
</pre>Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br />220-business67.web-hosting.com ESMTP Exim 4.95 #2 Fri, 05 Aug 11:28:02 -0400 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
<br /><pre>hello: 250-business67.web-hosting.com Hello localhost [197.242.98.221]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPE_CONNECT
250-AUTH PLAIN LOGIN
250 HELP
</pre><pre>from: 250 OK
</pre><pre>to: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
</pre>The following SMTP error was encountered: 550 "Your IP: 197.242.98.221 : Your domain  is not allowed in header From"
<br /><pre>quit: 221 business67.web-hosting.com closing connection
</pre>Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Fri, 05 Aug 16:27:53 +0100
From: &quot;PBO&quot; &lt;&gt;
Return-Path: &lt;&gt;
To: kuqib@mailinator.com
Subject: =?UTF-8?Q?Your=20activation=20code?=
Reply-To: &lt;&gt;
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;62e2aaffbfcce1.83381459&gt;
Mime-Version: 1.0

</pre>
in VENDORPATH\codeigniter4\shield\src\Authentication\Actions\EmailActivator.php on line 60.
 1 VENDORPATH\codeigniter4\shield\src\Controllers\ActionController.php(52): CodeIgniter\Shield\Authentication\Actions\EmailActivator->show()
 2 VENDORPATH\codeigniter4\shield\src\Controllers\ActionController.php(40): CodeIgniter\Shield\Controllers\ActionController->show()
 3 SYSTEMPATH\CodeIgniter.php(895): CodeIgniter\Shield\Controllers\ActionController->_remap('show')
 4 SYSTEMPATH\CodeIgniter.php(466): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\ActionController))
 5 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
```

**Comment by kenjis** [comment]
Thank you!

How about `MagicLinkController`?

File: src/Authentication/Actions/Email2FA.php [hunk 1]
```diff
@@ -71,14 +71,13 @@ public function handle(IncomingRequest $request)
...
-        if ($return === false) {
-            throw new RuntimeException('Cannot send email for user: ' . $user->email);
+        $email = emailer()->setFrom(setting('Email.fromEmail'), setting('Email.fromName') ?? '');
+        $email->setTo($user->email);
+        $email->setSubject(lang('Auth.email2FASubject'));
+        $email->setMessage(view(setting('Auth.views')['action_email_2fa_email'], ['code' => $identity->secret]));
+
+        if ($email->send(false) === false) {
+            throw new RuntimeException('Cannot send email for user: ' . $user->email . ' ' . $email->printDebugger(['headers']));
         }
```
Comment (kenjis) [inline src/Authentication/Actions/Email2FA.php:81]: Is it better to call `$email->clear()` here?

File: src/Authentication/Actions/Email2FA.php [hunk 2]
```diff
@@ -71,14 +71,13 @@ public function handle(IncomingRequest $request)
...
-
-        if ($return === false) {
-            throw new RuntimeException('Cannot send email for user: ' . $user->email);
+        $email = emailer()->setFrom(setting('Email.fromEmail'), setting('Email.fromName') ?? '');
+        $email->setTo($user->email);
+        $email->setSubject(lang('Auth.email2FASubject'));
+        $email->setMessage(view(setting('Auth.views')['action_email_2fa_email'], ['code' => $identity->secret]));
+
+        if ($email->send(false) === false) {
+            throw new RuntimeException('Cannot send email for user: ' . $user->email . ' ' . $email->printDebugger(['headers']));
```
Comment (kenjis) [inline src/Authentication/Actions/Email2FA.php:80]: How about this?

```suggestion
            throw new RuntimeException('Cannot send email for user: ' . $user->email . "\" . $email->printDebugger(['headers']));
```

**Comment by MGatner** [comment]
Why is the scope change on `createIdentity()` needed here? Can that be a separate PR?

File: src/Authentication/Actions/Email2FA.php (hunk 1 above)
Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:81]: I don't think so, since it is not a loop, and the `$email` variables are not being reinitialized. See [docs](https://codeigniter4.github.io/CodeIgniter4/libraries/email.html#clear).

File: src/Authentication/Actions/Email2FA.php (hunk 2 above)
Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:80]: This is good. 
Thank you.

**Comment by sammyskills** [comment]
> How about `MagicLinkController`?

 I think I totally missed that. I'll update the PR now.


> Why is the scope change on `createIdentity()` needed here? Can that be a separate PR?

Well, I felt since it is just a minor change, and since the issues are related, it can also be in the same PR. But, thanks for pointing it out. I'll create a separate PR for that.

File: src/Authentication/Actions/Email2FA.php (hunk 1 above)
Comment (kenjis) [reply src/Authentication/Actions/Email2FA.php:81]: The Email service is shared.
https://github.com/codeigniter4/shield/blob/44e65eff3043530e21337ffdb2d2f6c991a0e548/src/Helpers/email_helper.php#L44
If devs use the shared Email (`service('email')`) in their app, the state is not clear.

Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:81]: Does 'clearing' not mean the same as trying to reinitialise the email variables?

File: src/Authentication/Actions/Email2FA.php (hunk 2 above)
Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:80]: Just tried this, but it is returning syntax error. Is this what you were trying to explain:
```
throw new RuntimeException('Cannot send email for user: ' . $user->email . '"\"' . $email->printDebugger(['headers']));
```

Comment (kenjis) [reply src/Authentication/Actions/Email2FA.php:80]: Oh, sorry, I missed `n`. I mean `"\n"`.

Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php]: Thank you.

File: src/Authentication/Actions/Email2FA.php (hunk 1 above)
Comment (MGatner) [reply src/Authentication/Actions/Email2FA.php:81]: If necessary, probably a call to `clear()` should happen in the `emailer()` helper function.

Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:81]: Done, thank you.

Comment (kenjis) [reply src/Authentication/Actions/Email2FA.php:81]: No, it is not.
The issue is that a dev might use the Email object in their app after Shield send email.

`$email->send()` calls `clear()`. But you changed it to `$email->send(false)` that does not call `clear()`.
`emailer()` is a helper for Shield. It is not a framework helper, so a dev does not use it.

If a dev calls `service('email')`, the `clear()` you added in the `emailer()` is not called.
To begin with, `emailer()` calls `$email->initialize()` so you don't need to add `clear()`.

Comment (kenjis) [reply src/Authentication/Actions/Email2FA.php:81]: `service('email')` or `Services::email()` returns a shared instance by default.
It might be not good design.

Getting a new instance in `emailer()` may be better.
```diff
--- a/src/Helpers/email_helper.php
+++ b/src/Helpers/email_helper.php
@@ -41,7 +41,7 @@ function emailer(array $overrides = []): Email
         }
 
         /** @var Email $email */
-        $email = service('email');
+        $email = service('email', false);
 
         return $email->initialize($config);
     }
```

Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php:81]: Oh, thank you for the explanation.

**Review by kenjis — APPROVED** [review]
LGTM!

File: src/Authentication/Actions/Email2FA.php (hunk 1 above)
Comment (MGatner) [reply src/Authentication/Actions/Email2FA.php:81]: Using a single service makes testing harder, just need to be sure to inject the right class ahead of time. I think calling `clear()` before the final return is fine, but I also expect developers to handle this themselves. Any time `email` service is used there is a possibility that it is not in a "clean" state so should be initialized/cleaned. This is of course terrible design but will be fixed when `Mailer` is released.

Comment (kenjis) [reply src/Authentication/Actions/Email2FA.php:81]: Calling `clear()` before the final return does not make sense, becaue `initialize()` calls `clear()`.

Then, calling `clear()` after `throw new RuntimeException()` is the only way.
Otherwise this PR is a breaking change.

File: src/Authentication/Actions/Email2FA.php [hunk 3]
```diff
@@ -71,14 +71,13 @@ public function handle(IncomingRequest $request)
...
-
-        if ($return === false) {
-            throw new RuntimeException('Cannot send email for user: ' . $user->email);
+        $email = emailer()->setFrom(setting('Email.fromEmail'), setting('Email.fromName') ?? '');
+        $email->setTo($user->email);
+        $email->setSubject(lang('Auth.email2FASubject'));
+        $email->setMessage(view(setting('Auth.views')['action_email_2fa_email'], ['code' => $identity->secret]));
+
+        if ($email->send(false) === false) {
+            throw new RuntimeException('Cannot send email for user: ' . $user->email . '\n' . $email->printDebugger(['headers']));
```
Comment (kenjis) [inline src/Authentication/Actions/Email2FA.php:80]: `'\n'` is literal `'\n'`. I mean a line break.

```suggestion
            throw new RuntimeException('Cannot send email for user: ' . $user->email . "\n" . $email->printDebugger(['headers']));
```

File: src/Authentication/Actions/EmailActivator.php [hunk 4]
```diff
@@ -41,14 +41,13 @@ public function show(): string
...
-
-        if ($return === false) {
-            throw new RuntimeException('Cannot send email for user: ' . $user->email);
+        $email = emailer()->setFrom(setting('Email.fromEmail'), setting('Email.fromName') ?? '');
+        $email->setTo($userEmail);
+        $email->setSubject(lang('Auth.emailActivateSubject'));
+        $email->setMessage(view(setting('Auth.views')['action_email_activate_email'], ['code' => $code]));
+
+        if ($email->send(false) === false) {
+            throw new RuntimeException('Cannot send email for user: ' . $user->email . '\n' . $email->printDebugger(['headers']));
```
Comment (kenjis) [inline src/Authentication/Actions/EmailActivator.php:50]:
```suggestion
            throw new RuntimeException('Cannot send email for user: ' . $user->email . "\n" . $email->printDebugger(['headers']));
```

**Review by kenjis — CHANGES_REQUESTED** [review]
See my two comments.

File: src/Authentication/Actions/Email2FA.php (hunk 3 above)
Comment (sammyskills) [reply src/Authentication/Actions/Email2FA.php]: Done, thanks.

File: src/Authentication/Actions/EmailActivator.php (hunk 4 above)
Comment (sammyskills) [reply src/Authentication/Actions/EmailActivator.php]: Done, thank you.

File: src/Helpers/email_helper.php [hunk 5]
```diff
@@ -41,7 +41,7 @@ function emailer(array $overrides = []): Email
         }
 
         /** @var Email $email */
-        $email = service('email');
+        $email = service('email', false);
```
Comment (kenjis) [inline src/Helpers/email_helper.php:44]: Let's follow MGater's opinion and undo this here.

```suggestion
        $email = service('email');
```

**Comment by kenjis** [comment]
To keep the same behavior, please add ` $email->clear();`:
```php
        if ($email->send(false) === false) {
            throw new RuntimeException('Cannot send email for user: ' . $user->email . "\n" . $email->printDebugger(['headers']));
        }

        $email->clear();
```

File: src/Helpers/email_helper.php (hunk 5 above)
Comment (sammyskills) [reply src/Helpers/email_helper.php:44]: So, is the email still going to be `clear()`ed ?

Comment (kenjis) [reply src/Helpers/email_helper.php:44]: See my comment below.

Comment (sammyskills) [reply src/Helpers/email_helper.php]: Ok. 
Done that now.

**Review by kenjis — APPROVED** [review]
Thank you!

**Review by MGatner — APPROVED** [review]
Looks good! Thanks everyone.
