### PR TITLE
fix: workaround for email only registration/login

### LINKED ISSUE #224: Register without username
I register without username, gives error.

Error message:
https://user-images.githubusercontent.com/50026015/172833798-59665122-053b-407c-803d-474d617ddc9b.png

### PR DESCRIPTION
**Pull request by kenjis**
Fixes #224

### CODE REVIEW

File: src/Controllers/RegisterController.php [hunk 1]
```diff
@@ -66,6 +66,11 @@ public function registerAction(): RedirectResponse
 
         $user->fill($this->request->getPost($allowedPostFields));
 
+        // Workaround for email only registration/login
+        if ($user->username === null) {
+            $user->username = null;
+        }
```
Comment (MGatner) [inline src/Controllers/RegisterController.php:72]: We should definitely think about a better solution down the road, this is pretty hacky 😅
Alternate syntax:
```suggestion
        $user->username ??= null;
```

File: src/Models/UserModel.php [hunk 2]
```diff
@@ -222,6 +222,7 @@ public function save($data): bool
                 lang('Database.emptyDataset', ['update']),
             ];
             if (in_array($e->getMessage(), $messages, true)) {
+                // @TODO Why true? Shouldn't this workaround be removed?
```
Comment (MGatner) [inline src/Models/UserModel.php:225]: I am not a fan of the whole `save()` extension. Lonnie had trouble getting model callbacks to work because the entity isn't passed, but I think finding another way to handle these is important (eventually).

**Review by MGatner — APPROVED** [review]
Comment is optional, workaround looks good.

File: src/Controllers/RegisterController.php (hunk 1 above)
Comment (kenjis) [reply src/Controllers/RegisterController.php:72]: After all, the both codes are the same.
Both are funny!

This is a temporary hack, so no problem.

File: src/Models/UserModel.php (hunk 2 above)
Comment (lonnieezell) [reply src/Models/UserModel.php:225]: I think the thing to do is to fix CodeIgniter to pass the original data along in the Model callbacks, honestly. I think that would be helpful for many people.

**Comment by datamweb** [comment]
@kenjis It seems that changes to file `NothingPersonalValidator.php` should be applied to these **PR**.
https://github.com/codeigniter4/shield/blob/00023eee70d65c17cb9bd840a174885feb15bebd/src/Authentication/Passwords/NothingPersonalValidator.php#L15-L20

**Comment by kenjis** [comment]
@datamweb What do you mean?
NothingPersonalValidator is enabled by default, and I did not see any errors.

By the way, the file has functions staring with `\`.
https://github.com/codeigniter4/shield/blob/00023eee70d65c17cb9bd840a174885feb15bebd/src/Authentication/Passwords/NothingPersonalValidator.php#L23

File: src/Models/UserModel.php (hunk 2 above)
Comment (kenjis) [reply src/Models/UserModel.php:225]: > to fix CodeIgniter to pass the original data along in the Model callbacks

I agree with it.

**Comment by datamweb** [comment]
> What do you mean? 

@kenjis **I have such an error!!** and I used the following code in [55](https://github.com/codeigniter4/shield/blob/00023eee70d65c17cb9bd840a174885feb15bebd/src/Authentication/Passwords/NothingPersonalValidator.php#L55) and [163](https://github.com/codeigniter4/shield/blob/00023eee70d65c17cb9bd840a174885feb15bebd/src/Authentication/Passwords/NothingPersonalValidator.php#L163) to fix it.

```
         if(is_null($user->username)){
             return true;
         }
```
err

**Comment by kenjis** [comment]
@datamweb Oh, thanks! I'm using PHP 8.0, so I did not notice.

**Comment by kenjis** [comment]
@datamweb Fixed the error. Is this okay?

**Comment by datamweb** [comment]
> Is this okay?

@kenjis is okay.
Just for user friendliness, it's not better to make changes in

https://github.com/codeigniter4/shield/blob/00023eee70d65c17cb9bd840a174885feb15bebd/src/Collectors/Auth.php#L74

create?

**Comment by kenjis** [comment]
If the username is null, the toolbar output will be blank.
I'm okay with it.

Screenshot 2022-06-12 16 42 15

**Comment by datamweb** [comment]
Thanks @kenjis.

File: src/Authentication/Passwords/NothingPersonalValidator.php [hunk 3]
```diff
@@ -52,8 +52,8 @@ public function check(string $password, ?User $user = null): Result
      */
     protected function isNotPersonal(string $password, ?User $user): bool
     {
-        $userName = \strtolower($user->username);
-        $email    = \strtolower($user->email);
+        $userName = strtolower($user->username ?? '');
+        $email    = strtolower($user->email);
```
Comment (MGatner) [inline src/Authentication/Passwords/NothingPersonalValidator.php:56]: Should we anticipate users trying to work without emails?
```suggestion
        $email    = strtolower($user->email ?? '');
```

File: src/Models/UserModel.php (hunk 2 above)
Comment (MGatner) [reply src/Models/UserModel.php:225]: Sounds good! I am fine with this for now.

File: src/Authentication/Passwords/NothingPersonalValidator.php (hunk 3 above)
Comment (kenjis) [reply src/Authentication/Passwords/NothingPersonalValidator.php:56]: It is out of scope of this PR.

The current implementation requires email. If we support users without email, I guess more to work.

**Review by lonnieezell — APPROVED** [review]

File: src/Controllers/RegisterController.php (hunk 1 above)
Comment (nfaiz) [reply src/Controllers/RegisterController.php:72]: Since the username column is unique, why don't use email value as username for temporary hack?

Comment (kenjis) [reply src/Controllers/RegisterController.php:72]: I think we should not store data other than what the column name indicates.
It will only bring confusion.

Comment (nfaiz) [reply src/Controllers/RegisterController.php:72]: Yes, but it can only save one (1) row ATM.

Comment (MGatner) [reply src/Controllers/RegisterController.php:72]: This is a modification a developer could make for their instance, but using an email address as the username can be a security and privacy issue so this library has worked hard to keep them separate.
