### PR TITLE
fix: findByCredentials() returns User when email is empty string

### LINKED ISSUE #546: Bug: findByCredentials() returns User when email is empty string
### PHP Version

7.4

### CodeIgniter4 Version

4.2.10

### Shield Version

develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### Did you customize Shield?

No.

### What happened?

`findByCredentials()` returns a valid user object when the email parameter value is empty.

### Steps to Reproduce

Do this:
```
$users = model(UserModel);
$user = $users->findByCredentials(['email' => '']);
dd($user);
```
This returns a valid `CodeIgniter\Shield\Entities\User` instance. 

### Expected Output

I expect `null` to be returned as no email address was entered in the value field.

### Anything else?

However, if I add a space with the value like so: `$user = $users->findByCredentials(['email' => ' ']);`, I get `null`.

### PR DESCRIPTION
**Pull request by kenjis**
Fixes  #546

This is a case that `empty()` causes a bug.

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Thanks for the quick fix!

File: tests/Unit/UserModelTest.php [hunk 1]
```diff
@@ -45,6 +45,22 @@ public function testSaveInsertUser(): void
         ]);
     }
 
+    /**
+     * @see https://github.com/codeigniter4/shield/issues/546
+     */
+    public function testfindByCredentialsEmptyEmail(): void
```
Comment (datamweb) [inline tests/Unit/UserModelTest.php:51]:
```suggestion
    public function testFindByCredentialsEmptyEmail(): void
```

**Review by datamweb — APPROVED** [review]
Thanks, the code works fine.
